#! python
"""
Module Name: 1_processing
Affiliation: CIBR_WangtongfeiLab

Description:
    Prepare infrared mouse videos for DeepLabCut analysis. For non-runway videos,
    split each source video into left and right mouse videos, then run the
    customized DeepLabCut prediction workflow.

Functions:
    - get_split_video_paths: Collect split video paths generated by preprocessing.
    - draw_many_split_line: Save a visual guide for choosing the split point.
    - preprocess: Split non-runway videos into left and right videos.
    - analyze_videos: Run DeepLabCut analysis on original or split videos.
    - main: Load configuration and run the first-stage workflow.

Usage:
    python 1_processing.py cfg.yaml

Copyright:
    Copyright (c) CIBR_WangtongfeiLab.

Note:
    If this code is used in academic publication,
    please cite or acknowledge CIBR_WangtongfeiLab.
"""

import sys
import time
from pathlib import Path

import cv2

try:
    from utils import load_cfg, get_video_paths
except ImportError:
    import utils

    load_cfg = utils.load_cfg
    get_video_paths = utils.get_video_paths


cfg = None


def get_split_video_paths():
    """Collect generated split-video paths for downstream DLC analysis."""
    data_path = Path(cfg.Data_path)
    if data_path.is_file():
        split_dir = data_path.parent / data_path.stem / 'split_videos'
        videos = split_dir.glob('*.mp4')
    else:
        videos = data_path.glob('*/split_videos/*.mp4')
    return [str(video) for video in videos]


def draw_many_split_line(frame, saved_path, split_point):
    """Save a frame with candidate split lines and the configured split point."""
    h, w = frame.shape[:2]
    for line_ratio in [i / 10 for i in range(1, 10)]:
        x = int(round(w * line_ratio))
        cv2.line(frame, (x, 0), (x, h), (255, 255, 255), 1)
        cv2.putText(frame, f'{line_ratio}', (x, h - 10), 1, 1, (255, 255, 255), 1, lineType=cv2.LINE_AA)

    x = int(round(w * split_point))
    cv2.line(frame, (x, 0), (x, h), (0, 0, 255), 1)
    cv2.imwrite(str(saved_path), frame)


def preprocess():
    """Split each non-runway source video into left and right mouse videos."""
    split_point = cfg.Split_point
    videos = get_video_paths(cfg)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')

    for video_id, video_path in enumerate(videos):
        video_path = Path(video_path)
        print(f'Processing video {video_id + 1}/{len(videos)}: {video_path}')

        save_dir = video_path.parent / video_path.stem / 'split_videos'
        save_dir.mkdir(exist_ok=True, parents=True)

        cap = cv2.VideoCapture(str(video_path))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        ret, frame = cap.read()
        if ret:
            draw_many_split_line(frame, save_dir / 'split_line.jpg', cfg.Split_point)
            cap.set(cv2.CAP_PROP_POS_FRAMES, 0)

        line_x = int(width * split_point)
        left_width = line_x
        right_width = width - line_x
        if cfg.Exclude_temp_bar:
            right_width = cfg.Bar_roi[2] - 2 - line_x

        left_writer = cv2.VideoWriter(str(save_dir / f'{video_path.stem}_1.mp4'), fourcc, fps, (left_width, height))
        right_writer = cv2.VideoWriter(str(save_dir / f'{video_path.stem}_2.mp4'), fourcc, fps, (right_width, height))

        frame_id = 1
        while True:
            ret, frame = cap.read()
            if not ret:
                break

            print(f'\r{frame_id}/{frame_count}', end='')
            left_writer.write(frame[:, :left_width])
            if cfg.Exclude_temp_bar:
                right_writer.write(frame[:, left_width:cfg.Bar_roi[2] - 2])
            else:
                right_writer.write(frame[:, left_width:])
            frame_id += 1

        print()
        cap.release()
        left_writer.release()
        right_writer.release()


def analyze_videos():
    """Run customized DeepLabCut analysis on source videos or split videos."""
    if cfg.Runway_video is True:
        videos = get_video_paths(cfg)
    else:
        videos = get_split_video_paths()

    from predict_videos import analyze_videos

    analyze_videos(
        config=cfg.Config_path,
        videos=videos,
        videotype='',
        save_as_csv=True,
        Mask_polygon_vertexs=cfg.Mask_polygon_vertexs,
    )


def main():
    """Load configuration and execute preprocessing plus DLC prediction."""
    global cfg

    if len(sys.argv) < 2:
        print('Usage: python 1_processing.py <cfg.yaml>')
        return

    cfg = load_cfg(sys.argv[1])
    start_time = time.time()

    if not cfg.Runway_video:
        preprocess()
    analyze_videos()

    end_time = time.time()
    print(f'Elapsed time: {(end_time - start_time) / 60:.2f} mins')


if __name__ == '__main__':
    main()
